sudo: required
services:
    - docker

before_install:
    - docker build -t leetbox/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true leetbox/docker-react npm run test -- --coverage